### ISSUE TITLE
Example no more working

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter-python-api#37]
```bash
python3 request_data.py 
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f4db70bc588>
Traceback (most recent call last):
  File "request_data.py", line 47, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "request_data.py", line 28, in main
    response = await bma.node.summary(connection)
  File "/usr/lib/python3.5/site-packages/duniterpy/api/bma/node.py", line 55, in summary
    r = await client.requests_get('/summary')
  File "/usr/lib/python3.5/site-packages/duniterpy/api/bma/api.py", line 153, in requests_get
    logging.debug("Request : {0}".format(self.reverse_url(self.connection_handler.http_scheme, path)))
AttributeError: 'generator' object has no attribute 'http_scheme'
```

**Comment by floppy31** [comment]
hi, I'm starting to dive into the duniter protocol using duniter python api... My first exercice was to repair examples... see branch floppy_fix_example https://github.com/duniter/duniter-python-api/tree/floppy_fix_examples , I'm new in duniter/github/async prog so I let inso validate, and maybe close the ticket.. It works now, hope this helps.

**Comment by M5oul** [comment]
Merci pour ça. Ça débloque un peu.

Maintenant, je souhaite tester :
```bash
python3 send_certification.py 
Traceback (most recent call last):
  File "send_certification.py", line 4, in <module>
    import duniterpy.api.bma as bma
ModuleNotFoundError: No module named 'duniterpy'
```

C’est dans le dossier précédent. Comment faire en sorte que ça load cette lib?

Ah, en fait j’ai trouvé ! Faut un [PYTHONPATH](https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder).

**Comment by M5oul** [comment]
I tested every examples which are now working perfectly.

**Comment by vtexier** [comment]
BMAEndpoint.from_inline(BMA_ENDPOINT).conn_handler(AIOHTTP_SESSION) does not return a ConnectionHandler Object since https://github.com/duniter/duniter-python-api/commit/934c9776fe396fbf05101b3b237b3d879439bc39#diff-14d56a443768df8b8cd59bb33dc3a5af

but a generator object because of the yield command.

The conn_handler() docstring should be updated to reflect and explain that.

This line should be embedded in a try... except StopIterationError in case the generator is empty.

BMAEndpoint.from_inline(BMA_ENDPOINT).conn_handler_list(AIOHTTP_SESSION).next()
